### ISSUE TITLE
Test media permissions with iOS 15.6

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_image_pick_11#4]
Test permissions with iOS 15.6 (newest version as of 7/22/2022).  I have a iPhone 7 test device that you can use for testing.  You can also use an iOS simulator, which might be easier.

Test at least 1 file.

**Comment by caitlynbakery** [comment]
At the moment, I'm unable to build the project for IOS. There appears to be incompatibility for M1 Mac for arm64e architecture. The currently installed gem is x86_64. The issue is also discussed here: https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1/64901980#64901980

After discussion with @codetricity, I'm going to focus on Android.

**Comment by codetricity** [comment]
there's a longer explanation of the version of ruby (a computer language similar to python) installed on the Mac by default.
https://stackoverflow.com/a/66556339

That response has 190 upvotes.

There's an old version of ruby that ships with Macs.  I'm hoping that nothing breaks if I install a new version of ruby.

**Comment by caitlynbakery** [comment]
Ok, I have the permission granted, but need to add pictures to the ios local storage. Thanks for the help! :)

**Comment by codetricity** [comment]
nice job getting this working in 4f26a77539b7fd212d6fffb0bc3817326be44f28
